### ISSUE TITLE
Allow multiple widgets + allow to tweak template

### ISSUE THREAD

**Issue by portalzine** [edasque/RSSs_Ubersicht_Widget#7]
1. Currently its impossible to have multiple widgets, as it will always default back to the RSSs-Widget folder.
Well there is, when using a new target for the command ;)
2. I would like to tweak the list items a bit more. Would be nice to have a wrapper element around the list item text (simple span). Or another option would be to make the list item markup configurable.

Thanks 
Alex

**Comment by edasque** [comment]
Seems your two PR fixed those items, am I right? I merged them both, thank you.

**Comment by portalzine** [comment]
Yeah they did. Compiled my own main.go version to go with it. Will share once I have all changes in ;). 
I might also add a jsx version, using the new syntax.

**Comment by edasque** [comment]
Yes, please share your changes to the go file, I'd like to know what you've changed, I haven't revisited it since I initially wrote it to clean it up. I imagine it doesn't impact (1) and (2), does it?

**Comment by portalzine** [comment]
Yes will share it. 

I will be adding the default Go template parser to the mix. That way the output can be easily tweaked via the config and will also allow images or any other data  to be added from the feed elements.

**Comment by portalzine** [comment]
You can see the current update here:
[cubicfusion-uebersicht-rss-widget](https://github.com/portalzine/cubicfusion-uebersicht-rss-widget)

**Comment by edasque** [comment]
@portalzine nice job, I like it. Create a PR?

**Comment by portalzine** [comment]
PR is on its away :)
